menu:
- {name: 'About', url: '/about'}
- {name: 'Research', url: '/research'}
- {name: 'Resources', url: '/resources'}
- {name: 'Blog', url: '/posts'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

resources:
- {name: 'Vector Calculus', url: 'vector-calculus', course: False}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics', course: True, institution: "UChicago"}
- {name: 'Stellar Structures', url: 'stellar-structures', course: True, institution: "UCSC"}
- {name: 'Stellar Structures_uchic', url: 'stellar-structures', course: True, institution: "UChicago"}
- {name: 'Vector Calculus2', url: 'vector-calculus', course: False}
- {name: 'Quantum Mechanics_ucsc', url: 'quantum-mechanics', course: True, institution: "UCSC"}

social:
- {icon: 'github', link: 'https://github.com/astrodiegog', name: 'Github', handle: 'astrodiegog'}
- {icon: 'twitter', link: 'https://twitter.com/astrodiegog', name: 'Twitter', handle: 'astrodiegog'}
- {icon: 'instagram', link: 'https://instagram.com/astrodiego', name: 'Instagram', handle: 'astrodiego'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/diego-garza-0b0620174/', name: 'LinkedIn', handle: 'diego-garza-0b0620174'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0003-0226-6988', name: 'ORCID', handle: '0009-0003-0226-6988'}

contacts:
- {name: 'Diego Garza', title: 'Graduate Student', department: 'Astronomy & Astrophysics', institution: 'University of California: Santa Cruz', institution_address: '1156 High St Santa Cruz, CA', email: 'digarza@ucsc.edu', office: 'Interdisciplinary Sciences Building', image: 'assets/img/contact.jpg'}
