- title: 'SEDS-UChicago Vice President, Treasurer'
  dates: 'March 2020 – June 2023'
  description: ['Plan and coordinate weekly meetings, events, and workshops to help students with model rocketry and high-powered rocketry certification',
  'Outreach and coordinate logistics to industry professionals to plan for the national conference SpaceVision 2022 hosted at UChicago',
  'Manage the funds for my school’s SEDS chapter. Write and defend grant proposals from SEDS-USA and UChicago Student Government’s Financial Committee']
  link: ''

- title: 'Moneythink Mentor'
  dates: 'November 2019 – June 2023'
  description: ['Mentor local Chicago high school students on the importance and process of financial literacy. Provide advice on post-graduation plans including college and trade school']
  link: 'https://www.uchicagomoneythink.com'

- title: 'SACNAS Secretary, Member'
  dates: 'October 2020 – June 2022'
  description: ['Develop events and programming to engage with minority students on campus and take notes during leadership meetings']
  link: ''

- title: 'Kavli Institute Space Explorers Instructor'
  dates: 'June 2021 – January 2022'
  description: ['Design, develop, and document summer curriculum for high school students']
  link: 'https://kavlicosmo.uchicago.edu/outreach/space-explorers/'

- title: 'Odyssey Community Scholars Fellow'
  dates: 'September 2020 – June 2021'
  description: ['Write, edit, and develop a First-Generation Low-Income Catalog documenting resources and providing advice from shared experiences at the University of Chicago for incoming students from disadvantaged backgrounds',
  'Share important issues and suggested solutions with the Dean of Students in the University as a speaker for the Odyssey Scholar community']
  link: ''
